CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE memes (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  url TEXT NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE
);